ARG KEYCLOAK_BASE_IMAGE=quay.io/keycloak/keycloak:26.6
FROM ${KEYCLOAK_BASE_IMAGE} AS builder

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_DB=postgres

WORKDIR /opt/keycloak

# Development-only certificate for the local Docker stack.
RUN keytool -genkeypair \
    -storepass password \
    -storetype PKCS12 \
    -keyalg RSA \
    -keysize 2048 \
    -dname "CN=server" \
    -alias server \
    -ext "SAN:c=DNS:localhost,IP:127.0.0.1" \
    -keystore conf/server.keystore

FROM ${KEYCLOAK_BASE_IMAGE}

COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY realm-drs.json /opt/keycloak/data/import/realm-drs.json
COPY start-keycloak.sh /opt/keycloak/start-keycloak.sh
USER root
RUN chmod 0755 /opt/keycloak/start-keycloak.sh
USER keycloak

RUN /opt/keycloak/bin/kc.sh show-config

ENTRYPOINT ["/opt/keycloak/start-keycloak.sh"]
