Title: Starbase
Subtitle: iRODS Grid Stack
RestAPIBaseURL: http://localhost:8080
OIDCEndpoint: /web/login
# oidc endpoint configs
OIDCAuthorizationEndpoint: https://localhost:8443/realms/drs/protocol/openid-connect/auth
OIDCTokenEndpoint: https://localhost:8443/realms/drs/protocol/openid-connect/token
OIDCClientID: starbase-spa
OIDCScope: openid profile email
OIDCRedirectPath: /auth/callback
S3AdminEnabled: true

AuthMode:
  - Mode: native
    AuthName: iRODS native
  - Mode: pam
    AuthName: iRODS PAM
